---
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
    
- name: start app
  become: yes
  shell: |
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: udapeople-prod.cvsoykqofeaz.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: postgres
    
- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
- name: check pm2 status
  become: yes
  shell: |
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines